/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Map;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;
import org.apache.commons.collections.map.HashedMap;

/**
 *
 * @author Gaby
 */
public class frmReporteViaje extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReporteViaje
     */
    public frmReporteViaje() {
        initComponents();
        String formato = "YYYY-MM-dd";
        SimpleDateFormat sdf = new SimpleDateFormat(formato);
        fecha.setDateFormat(sdf);
         
    }
    public void imprimirReporte() throws HeadlessException {
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            conexionViaje cc = new conexionViaje();
            Connection cn = cc.conectar();
            Map parametros = new HashedMap();
            if (cmbBuscar.getSelectedItem().equals("GENERAL")) {
                //parametros.put("placa", txtReportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteViaje.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, null, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                menú.jDesktopPane1.add(frame);
                frame.setVisible(true);
            } if (cmbBuscar.getSelectedItem().equals("FECHA SALIDA")) {
//                JOptionPane.showMessageDialog(null, fecha.getText() );
                parametros.put("fechaSalida", fecha.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteViajesxFecha.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                menú.jDesktopPane1.add(frame);
                frame.setVisible(true);
            } if (cmbBuscar.getSelectedItem().equals("FECHA LLEGADA")) {
                parametros.put("fechaLlegada", fecha.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteViajesFechaLlegada.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                menú.jDesktopPane1.add(frame);
                frame.setVisible(true); 
            } if(cmbBuscar.getSelectedItem().equals("SELECCIONE")){
                JOptionPane.showMessageDialog(null, "SELECCIONE OPCION");
            }
            
            
            //JasperViewer.viewReport(imprimir,false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "1" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbBuscar = new javax.swing.JComboBox<>();
        btnReporte = new javax.swing.JButton();
        fecha = new datechooser.beans.DateChooserCombo();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("BUscar por:");

        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "GENERAL", "FECHA SALIDA", "FECHA LLEGADA" }));
        cmbBuscar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBuscarItemStateChanged(evt);
            }
        });
        cmbBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBuscarMouseClicked(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporte)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporte)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        imprimirReporte();        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    private void cmbBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBuscarMouseClicked
//         if (cmbBuscar.getSelectedItem().equals("GENERAL")) {
//             fecha.setEnabled(false);
//         }else{
//             fecha.setEnabled(true);
//         }
            // TODO add your handling code here:
    }//GEN-LAST:event_cmbBuscarMouseClicked

    private void cmbBuscarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBuscarItemStateChanged
         if (cmbBuscar.getSelectedItem().equals("GENERAL")) {
             fecha.setEnabled(false);
         }else{
             fecha.setEnabled(true);
         }// TODO add your handling code here:
    }//GEN-LAST:event_cmbBuscarItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox<String> cmbBuscar;
    private datechooser.beans.DateChooserCombo fecha;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
