/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.util.Map;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.collections.map.HashedMap;

/**
 *
 * @author ander
 */
public class frmReporteAutoxPlaca extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReporteAutoxPlaca
     */
    public frmReporteAutoxPlaca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtReportes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Buscar por:");

        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "GENERAL", "PLACA", "MARCA", "MODELO", "AÑO" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imprimirReporte();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
            if (jComboBox1.getSelectedItem().equals("GENERAL")) {
                txtReportes.setEnabled(false);
            }else{
                 txtReportes.setEnabled(true);
            }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    public void imprimirReporte() throws HeadlessException {
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            conexionViaje cc = new conexionViaje();
            Connection cn = cc.conectar();
            Map parametros = new HashedMap();
            if (jComboBox1.getSelectedItem().equals("PLACA")) {
                parametros.put("placa", txtReportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAutoxPlaca.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                menú.jDesktopPane1.add(frame);
                frame.setVisible(true);
            } if (jComboBox1.getSelectedItem().equals("MODELO")) {
                parametros.put("modelo", txtReportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAutoxModelo.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                menú.jDesktopPane1.add(frame);
                frame.setVisible(true);
            } if (jComboBox1.getSelectedItem().equals("MARCA")) {
                parametros.put("marca", txtReportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAutoxMarca.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                menú.jDesktopPane1.add(frame);
                frame.setVisible(true);
            } if (jComboBox1.getSelectedItem().equals("AÑO")) {
                parametros.put("año", txtReportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAutoxAño.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                menú.jDesktopPane1.add(frame);
                frame.setVisible(true);
            } if(jComboBox1.getSelectedItem().equals("SELECCIONE")){
                JOptionPane.showMessageDialog(null, "SELECCIONE OPCION");
            } if (jComboBox1.getSelectedItem().equals("GENERAL")) {
//                parametros.put("año", txtReportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAuto.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                menú.jDesktopPane1.add(frame);
                frame.setVisible(true);
            }
            
            
            //JasperViewer.viewReport(imprimir,false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "1" + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteAutoxPlaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteAutoxPlaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteAutoxPlaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteAutoxPlaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteAutoxPlaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtReportes;
    // End of variables declaration//GEN-END:variables
}
